server:
  name: "places-svc"
  port: ":8004"
  log:
    level: "debug"
    format: "text"
  timeouts:
    read: 15 #seconds
    read_header: 15 #seconds
    write: 15 #seconds
    idle: 60 #seconds

database:
  sql:
    url: "postgresql://postgres:postgres@localhost:7777/postgres?sslmode=disable"
  redis:
    addr: "localhost:7200"
    password: "example"
    db: 0
    lifetime: 15 #minutes

jwt:
  user:
    access_token:
      secret_key: "UnG06MAU2i1Mvqf8"
  service:
    secret_key: "servicesuperkey"

kafka:
  brokers:
    - "re-news-kafka:XXXX"

swagger:
  enabled: true
  url: "/swagger"
  port: "XXXX"

properties:
  residence:
    api_key: "apikey" #form https://rapidapi.com/wirefreethought/api/geodb-cities