/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassLocaleDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassLocaleDataAttributes{}

// ClassLocaleDataAttributes struct for ClassLocaleDataAttributes
type ClassLocaleDataAttributes struct {
	// Class name
	Name string `json:"name"`
}

type _ClassLocaleDataAttributes ClassLocaleDataAttributes

// NewClassLocaleDataAttributes instantiates a new ClassLocaleDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassLocaleDataAttributes(name string) *ClassLocaleDataAttributes {
	this := ClassLocaleDataAttributes{}
	this.Name = name
	return &this
}

// NewClassLocaleDataAttributesWithDefaults instantiates a new ClassLocaleDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassLocaleDataAttributesWithDefaults() *ClassLocaleDataAttributes {
	this := ClassLocaleDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *ClassLocaleDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClassLocaleDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClassLocaleDataAttributes) SetName(v string) {
	o.Name = v
}

func (o ClassLocaleDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassLocaleDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ClassLocaleDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassLocaleDataAttributes := _ClassLocaleDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassLocaleDataAttributes)

	if err != nil {
		return err
	}

	*o = ClassLocaleDataAttributes(varClassLocaleDataAttributes)

	return err
}

type NullableClassLocaleDataAttributes struct {
	value *ClassLocaleDataAttributes
	isSet bool
}

func (v NullableClassLocaleDataAttributes) Get() *ClassLocaleDataAttributes {
	return v.value
}

func (v *NullableClassLocaleDataAttributes) Set(val *ClassLocaleDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableClassLocaleDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableClassLocaleDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassLocaleDataAttributes(val *ClassLocaleDataAttributes) *NullableClassLocaleDataAttributes {
	return &NullableClassLocaleDataAttributes{value: val, isSet: true}
}

func (v NullableClassLocaleDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassLocaleDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


