/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Timetable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Timetable{}

// Timetable struct for Timetable
type Timetable struct {
	Data TimetableData `json:"data"`
}

type _Timetable Timetable

// NewTimetable instantiates a new Timetable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimetable(data TimetableData) *Timetable {
	this := Timetable{}
	this.Data = data
	return &this
}

// NewTimetableWithDefaults instantiates a new Timetable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimetableWithDefaults() *Timetable {
	this := Timetable{}
	return &this
}

// GetData returns the Data field value
func (o *Timetable) GetData() TimetableData {
	if o == nil {
		var ret TimetableData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Timetable) GetDataOk() (*TimetableData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Timetable) SetData(v TimetableData) {
	o.Data = v
}

func (o Timetable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Timetable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Timetable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimetable := _Timetable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimetable)

	if err != nil {
		return err
	}

	*o = Timetable(varTimetable)

	return err
}

type NullableTimetable struct {
	value *Timetable
	isSet bool
}

func (v NullableTimetable) Get() *Timetable {
	return v.value
}

func (v *NullableTimetable) Set(val *Timetable) {
	v.value = val
	v.isSet = true
}

func (v NullableTimetable) IsSet() bool {
	return v.isSet
}

func (v *NullableTimetable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimetable(val *Timetable) *NullableTimetable {
	return &NullableTimetable{value: val, isSet: true}
}

func (v NullableTimetable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimetable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


