/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForPlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForPlace{}

// SetLocalesForPlace struct for SetLocalesForPlace
type SetLocalesForPlace struct {
	Data SetLocalesForPlaceData `json:"data"`
}

type _SetLocalesForPlace SetLocalesForPlace

// NewSetLocalesForPlace instantiates a new SetLocalesForPlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForPlace(data SetLocalesForPlaceData) *SetLocalesForPlace {
	this := SetLocalesForPlace{}
	this.Data = data
	return &this
}

// NewSetLocalesForPlaceWithDefaults instantiates a new SetLocalesForPlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForPlaceWithDefaults() *SetLocalesForPlace {
	this := SetLocalesForPlace{}
	return &this
}

// GetData returns the Data field value
func (o *SetLocalesForPlace) GetData() SetLocalesForPlaceData {
	if o == nil {
		var ret SetLocalesForPlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForPlace) GetDataOk() (*SetLocalesForPlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetLocalesForPlace) SetData(v SetLocalesForPlaceData) {
	o.Data = v
}

func (o SetLocalesForPlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForPlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetLocalesForPlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForPlace := _SetLocalesForPlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForPlace)

	if err != nil {
		return err
	}

	*o = SetLocalesForPlace(varSetLocalesForPlace)

	return err
}

type NullableSetLocalesForPlace struct {
	value *SetLocalesForPlace
	isSet bool
}

func (v NullableSetLocalesForPlace) Get() *SetLocalesForPlace {
	return v.value
}

func (v *NullableSetLocalesForPlace) Set(val *SetLocalesForPlace) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForPlace) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForPlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForPlace(val *SetLocalesForPlace) *NullableSetLocalesForPlace {
	return &NullableSetLocalesForPlace{value: val, isSet: true}
}

func (v NullableSetLocalesForPlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForPlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


