/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocaleForClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocaleForClassData{}

// SetLocaleForClassData struct for SetLocaleForClassData
type SetLocaleForClassData struct {
	// class_code
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SetLocaleForClassDataAttributes `json:"attributes"`
}

type _SetLocaleForClassData SetLocaleForClassData

// NewSetLocaleForClassData instantiates a new SetLocaleForClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocaleForClassData(id string, type_ string, attributes SetLocaleForClassDataAttributes) *SetLocaleForClassData {
	this := SetLocaleForClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSetLocaleForClassDataWithDefaults instantiates a new SetLocaleForClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocaleForClassDataWithDefaults() *SetLocaleForClassData {
	this := SetLocaleForClassData{}
	return &this
}

// GetId returns the Id field value
func (o *SetLocaleForClassData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClassData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetLocaleForClassData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SetLocaleForClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SetLocaleForClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SetLocaleForClassData) GetAttributes() SetLocaleForClassDataAttributes {
	if o == nil {
		var ret SetLocaleForClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClassData) GetAttributesOk() (*SetLocaleForClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SetLocaleForClassData) SetAttributes(v SetLocaleForClassDataAttributes) {
	o.Attributes = v
}

func (o SetLocaleForClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocaleForClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SetLocaleForClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocaleForClassData := _SetLocaleForClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocaleForClassData)

	if err != nil {
		return err
	}

	*o = SetLocaleForClassData(varSetLocaleForClassData)

	return err
}

type NullableSetLocaleForClassData struct {
	value *SetLocaleForClassData
	isSet bool
}

func (v NullableSetLocaleForClassData) Get() *SetLocaleForClassData {
	return v.value
}

func (v *NullableSetLocaleForClassData) Set(val *SetLocaleForClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocaleForClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocaleForClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocaleForClassData(val *SetLocaleForClassData) *NullableSetLocaleForClassData {
	return &NullableSetLocaleForClassData{value: val, isSet: true}
}

func (v NullableSetLocaleForClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocaleForClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


