/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceLocalesCollectionDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceLocalesCollectionDataInner{}

// PlaceLocalesCollectionDataInner struct for PlaceLocalesCollectionDataInner
type PlaceLocalesCollectionDataInner struct {
	// The type of the related resource
	Type string `json:"type"`
	// The ID of the related resource
	Id string `json:"id"`
}

type _PlaceLocalesCollectionDataInner PlaceLocalesCollectionDataInner

// NewPlaceLocalesCollectionDataInner instantiates a new PlaceLocalesCollectionDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceLocalesCollectionDataInner(type_ string, id string) *PlaceLocalesCollectionDataInner {
	this := PlaceLocalesCollectionDataInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewPlaceLocalesCollectionDataInnerWithDefaults instantiates a new PlaceLocalesCollectionDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceLocalesCollectionDataInnerWithDefaults() *PlaceLocalesCollectionDataInner {
	this := PlaceLocalesCollectionDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *PlaceLocalesCollectionDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceLocalesCollectionDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceLocalesCollectionDataInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *PlaceLocalesCollectionDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlaceLocalesCollectionDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlaceLocalesCollectionDataInner) SetId(v string) {
	o.Id = v
}

func (o PlaceLocalesCollectionDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceLocalesCollectionDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *PlaceLocalesCollectionDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceLocalesCollectionDataInner := _PlaceLocalesCollectionDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceLocalesCollectionDataInner)

	if err != nil {
		return err
	}

	*o = PlaceLocalesCollectionDataInner(varPlaceLocalesCollectionDataInner)

	return err
}

type NullablePlaceLocalesCollectionDataInner struct {
	value *PlaceLocalesCollectionDataInner
	isSet bool
}

func (v NullablePlaceLocalesCollectionDataInner) Get() *PlaceLocalesCollectionDataInner {
	return v.value
}

func (v *NullablePlaceLocalesCollectionDataInner) Set(val *PlaceLocalesCollectionDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceLocalesCollectionDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceLocalesCollectionDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceLocalesCollectionDataInner(val *PlaceLocalesCollectionDataInner) *NullablePlaceLocalesCollectionDataInner {
	return &NullablePlaceLocalesCollectionDataInner{value: val, isSet: true}
}

func (v NullablePlaceLocalesCollectionDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceLocalesCollectionDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


