/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClassData{}

// CreateClassData struct for CreateClassData
type CreateClassData struct {
	// class code
	Id string `json:"id"`
	// Resource type
	Type string `json:"type"`
	Attributes CreateClassDataAttributes `json:"attributes"`
}

type _CreateClassData CreateClassData

// NewCreateClassData instantiates a new CreateClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClassData(id string, type_ string, attributes CreateClassDataAttributes) *CreateClassData {
	this := CreateClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateClassDataWithDefaults instantiates a new CreateClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClassDataWithDefaults() *CreateClassData {
	this := CreateClassData{}
	return &this
}

// GetId returns the Id field value
func (o *CreateClassData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateClassData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateClassData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CreateClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateClassData) GetAttributes() CreateClassDataAttributes {
	if o == nil {
		var ret CreateClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateClassData) GetAttributesOk() (*CreateClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateClassData) SetAttributes(v CreateClassDataAttributes) {
	o.Attributes = v
}

func (o CreateClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClassData := _CreateClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateClassData)

	if err != nil {
		return err
	}

	*o = CreateClassData(varCreateClassData)

	return err
}

type NullableCreateClassData struct {
	value *CreateClassData
	isSet bool
}

func (v NullableCreateClassData) Get() *CreateClassData {
	return v.value
}

func (v *NullableCreateClassData) Set(val *CreateClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClassData(val *CreateClassData) *NullableCreateClassData {
	return &NullableCreateClassData{value: val, isSet: true}
}

func (v NullableCreateClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


