/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceRelationshipsCity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceRelationshipsCity{}

// PlaceRelationshipsCity struct for PlaceRelationshipsCity
type PlaceRelationshipsCity struct {
	Links PlaceRelationshipsCityLinks `json:"links"`
	Data Items `json:"data"`
}

type _PlaceRelationshipsCity PlaceRelationshipsCity

// NewPlaceRelationshipsCity instantiates a new PlaceRelationshipsCity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceRelationshipsCity(links PlaceRelationshipsCityLinks, data Items) *PlaceRelationshipsCity {
	this := PlaceRelationshipsCity{}
	this.Links = links
	this.Data = data
	return &this
}

// NewPlaceRelationshipsCityWithDefaults instantiates a new PlaceRelationshipsCity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceRelationshipsCityWithDefaults() *PlaceRelationshipsCity {
	this := PlaceRelationshipsCity{}
	return &this
}

// GetLinks returns the Links field value
func (o *PlaceRelationshipsCity) GetLinks() PlaceRelationshipsCityLinks {
	if o == nil {
		var ret PlaceRelationshipsCityLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PlaceRelationshipsCity) GetLinksOk() (*PlaceRelationshipsCityLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *PlaceRelationshipsCity) SetLinks(v PlaceRelationshipsCityLinks) {
	o.Links = v
}

// GetData returns the Data field value
func (o *PlaceRelationshipsCity) GetData() Items {
	if o == nil {
		var ret Items
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceRelationshipsCity) GetDataOk() (*Items, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PlaceRelationshipsCity) SetData(v Items) {
	o.Data = v
}

func (o PlaceRelationshipsCity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceRelationshipsCity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceRelationshipsCity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceRelationshipsCity := _PlaceRelationshipsCity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceRelationshipsCity)

	if err != nil {
		return err
	}

	*o = PlaceRelationshipsCity(varPlaceRelationshipsCity)

	return err
}

type NullablePlaceRelationshipsCity struct {
	value *PlaceRelationshipsCity
	isSet bool
}

func (v NullablePlaceRelationshipsCity) Get() *PlaceRelationshipsCity {
	return v.value
}

func (v *NullablePlaceRelationshipsCity) Set(val *PlaceRelationshipsCity) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceRelationshipsCity) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceRelationshipsCity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceRelationshipsCity(val *PlaceRelationshipsCity) *NullablePlaceRelationshipsCity {
	return &NullablePlaceRelationshipsCity{value: val, isSet: true}
}

func (v NullablePlaceRelationshipsCity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceRelationshipsCity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


