/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimetableInterval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimetableInterval{}

// TimetableInterval struct for TimetableInterval
type TimetableInterval struct {
	From TimeMoment `json:"from"`
	To TimeMoment `json:"to"`
}

type _TimetableInterval TimetableInterval

// NewTimetableInterval instantiates a new TimetableInterval object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimetableInterval(from TimeMoment, to TimeMoment) *TimetableInterval {
	this := TimetableInterval{}
	this.From = from
	this.To = to
	return &this
}

// NewTimetableIntervalWithDefaults instantiates a new TimetableInterval object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimetableIntervalWithDefaults() *TimetableInterval {
	this := TimetableInterval{}
	return &this
}

// GetFrom returns the From field value
func (o *TimetableInterval) GetFrom() TimeMoment {
	if o == nil {
		var ret TimeMoment
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *TimetableInterval) GetFromOk() (*TimeMoment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *TimetableInterval) SetFrom(v TimeMoment) {
	o.From = v
}

// GetTo returns the To field value
func (o *TimetableInterval) GetTo() TimeMoment {
	if o == nil {
		var ret TimeMoment
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *TimetableInterval) GetToOk() (*TimeMoment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *TimetableInterval) SetTo(v TimeMoment) {
	o.To = v
}

func (o TimetableInterval) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimetableInterval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *TimetableInterval) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimetableInterval := _TimetableInterval{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimetableInterval)

	if err != nil {
		return err
	}

	*o = TimetableInterval(varTimetableInterval)

	return err
}

type NullableTimetableInterval struct {
	value *TimetableInterval
	isSet bool
}

func (v NullableTimetableInterval) Get() *TimetableInterval {
	return v.value
}

func (v *NullableTimetableInterval) Set(val *TimetableInterval) {
	v.value = val
	v.isSet = true
}

func (v NullableTimetableInterval) IsSet() bool {
	return v.isSet
}

func (v *NullableTimetableInterval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimetableInterval(val *TimetableInterval) *NullableTimetableInterval {
	return &NullableTimetableInterval{value: val, isSet: true}
}

func (v NullableTimetableInterval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimetableInterval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


