/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetPlaceLocaleDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetPlaceLocaleDataAttributes{}

// SetPlaceLocaleDataAttributes struct for SetPlaceLocaleDataAttributes
type SetPlaceLocaleDataAttributes struct {
	// Locale name
	Name string `json:"name"`
	// Locale description
	Description string `json:"description"`
}

type _SetPlaceLocaleDataAttributes SetPlaceLocaleDataAttributes

// NewSetPlaceLocaleDataAttributes instantiates a new SetPlaceLocaleDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetPlaceLocaleDataAttributes(name string, description string) *SetPlaceLocaleDataAttributes {
	this := SetPlaceLocaleDataAttributes{}
	this.Name = name
	this.Description = description
	return &this
}

// NewSetPlaceLocaleDataAttributesWithDefaults instantiates a new SetPlaceLocaleDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetPlaceLocaleDataAttributesWithDefaults() *SetPlaceLocaleDataAttributes {
	this := SetPlaceLocaleDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *SetPlaceLocaleDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetPlaceLocaleDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetPlaceLocaleDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SetPlaceLocaleDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SetPlaceLocaleDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SetPlaceLocaleDataAttributes) SetDescription(v string) {
	o.Description = v
}

func (o SetPlaceLocaleDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetPlaceLocaleDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *SetPlaceLocaleDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetPlaceLocaleDataAttributes := _SetPlaceLocaleDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetPlaceLocaleDataAttributes)

	if err != nil {
		return err
	}

	*o = SetPlaceLocaleDataAttributes(varSetPlaceLocaleDataAttributes)

	return err
}

type NullableSetPlaceLocaleDataAttributes struct {
	value *SetPlaceLocaleDataAttributes
	isSet bool
}

func (v NullableSetPlaceLocaleDataAttributes) Get() *SetPlaceLocaleDataAttributes {
	return v.value
}

func (v *NullableSetPlaceLocaleDataAttributes) Set(val *SetPlaceLocaleDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSetPlaceLocaleDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSetPlaceLocaleDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetPlaceLocaleDataAttributes(val *SetPlaceLocaleDataAttributes) *NullableSetPlaceLocaleDataAttributes {
	return &NullableSetPlaceLocaleDataAttributes{value: val, isSet: true}
}

func (v NullableSetPlaceLocaleDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetPlaceLocaleDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


