/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForClass{}

// SetLocalesForClass struct for SetLocalesForClass
type SetLocalesForClass struct {
	Data SetLocalesForClassData `json:"data"`
}

type _SetLocalesForClass SetLocalesForClass

// NewSetLocalesForClass instantiates a new SetLocalesForClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForClass(data SetLocalesForClassData) *SetLocalesForClass {
	this := SetLocalesForClass{}
	this.Data = data
	return &this
}

// NewSetLocalesForClassWithDefaults instantiates a new SetLocalesForClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForClassWithDefaults() *SetLocalesForClass {
	this := SetLocalesForClass{}
	return &this
}

// GetData returns the Data field value
func (o *SetLocalesForClass) GetData() SetLocalesForClassData {
	if o == nil {
		var ret SetLocalesForClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClass) GetDataOk() (*SetLocalesForClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetLocalesForClass) SetData(v SetLocalesForClassData) {
	o.Data = v
}

func (o SetLocalesForClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetLocalesForClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForClass := _SetLocalesForClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForClass)

	if err != nil {
		return err
	}

	*o = SetLocalesForClass(varSetLocalesForClass)

	return err
}

type NullableSetLocalesForClass struct {
	value *SetLocalesForClass
	isSet bool
}

func (v NullableSetLocalesForClass) Get() *SetLocalesForClass {
	return v.value
}

func (v *NullableSetLocalesForClass) Set(val *SetLocalesForClass) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForClass) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForClass(val *SetLocalesForClass) *NullableSetLocalesForClass {
	return &NullableSetLocalesForClass{value: val, isSet: true}
}

func (v NullableSetLocalesForClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


