/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClass{}

// CreateClass struct for CreateClass
type CreateClass struct {
	Data CreateClassData `json:"data"`
}

type _CreateClass CreateClass

// NewCreateClass instantiates a new CreateClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClass(data CreateClassData) *CreateClass {
	this := CreateClass{}
	this.Data = data
	return &this
}

// NewCreateClassWithDefaults instantiates a new CreateClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClassWithDefaults() *CreateClass {
	this := CreateClass{}
	return &this
}

// GetData returns the Data field value
func (o *CreateClass) GetData() CreateClassData {
	if o == nil {
		var ret CreateClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateClass) GetDataOk() (*CreateClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateClass) SetData(v CreateClassData) {
	o.Data = v
}

func (o CreateClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateClass := _CreateClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateClass)

	if err != nil {
		return err
	}

	*o = CreateClass(varCreateClass)

	return err
}

type NullableCreateClass struct {
	value *CreateClass
	isSet bool
}

func (v NullableCreateClass) Get() *CreateClass {
	return v.value
}

func (v *NullableCreateClass) Set(val *CreateClass) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClass) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClass(val *CreateClass) *NullableCreateClass {
	return &NullableCreateClass{value: val, isSet: true}
}

func (v NullableCreateClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


