/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceCollection{}

// PlaceCollection struct for PlaceCollection
type PlaceCollection struct {
	Data []PlaceData `json:"data"`
}

type _PlaceCollection PlaceCollection

// NewPlaceCollection instantiates a new PlaceCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceCollection(data []PlaceData) *PlaceCollection {
	this := PlaceCollection{}
	this.Data = data
	return &this
}

// NewPlaceCollectionWithDefaults instantiates a new PlaceCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceCollectionWithDefaults() *PlaceCollection {
	this := PlaceCollection{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceCollection) GetData() []PlaceData {
	if o == nil {
		var ret []PlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceCollection) GetDataOk() ([]PlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PlaceCollection) SetData(v []PlaceData) {
	o.Data = v
}

func (o PlaceCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceCollection := _PlaceCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceCollection)

	if err != nil {
		return err
	}

	*o = PlaceCollection(varPlaceCollection)

	return err
}

type NullablePlaceCollection struct {
	value *PlaceCollection
	isSet bool
}

func (v NullablePlaceCollection) Get() *PlaceCollection {
	return v.value
}

func (v *NullablePlaceCollection) Set(val *PlaceCollection) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceCollection) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceCollection(val *PlaceCollection) *NullablePlaceCollection {
	return &NullablePlaceCollection{value: val, isSet: true}
}

func (v NullablePlaceCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


