/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassLocaleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassLocaleData{}

// ClassLocaleData struct for ClassLocaleData
type ClassLocaleData struct {
	// class_code + locale
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes ClassLocaleDataAttributes `json:"attributes"`
}

type _ClassLocaleData ClassLocaleData

// NewClassLocaleData instantiates a new ClassLocaleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassLocaleData(id string, type_ string, attributes ClassLocaleDataAttributes) *ClassLocaleData {
	this := ClassLocaleData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewClassLocaleDataWithDefaults instantiates a new ClassLocaleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassLocaleDataWithDefaults() *ClassLocaleData {
	this := ClassLocaleData{}
	return &this
}

// GetId returns the Id field value
func (o *ClassLocaleData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClassLocaleData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClassLocaleData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ClassLocaleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClassLocaleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClassLocaleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ClassLocaleData) GetAttributes() ClassLocaleDataAttributes {
	if o == nil {
		var ret ClassLocaleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ClassLocaleData) GetAttributesOk() (*ClassLocaleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ClassLocaleData) SetAttributes(v ClassLocaleDataAttributes) {
	o.Attributes = v
}

func (o ClassLocaleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassLocaleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ClassLocaleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassLocaleData := _ClassLocaleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassLocaleData)

	if err != nil {
		return err
	}

	*o = ClassLocaleData(varClassLocaleData)

	return err
}

type NullableClassLocaleData struct {
	value *ClassLocaleData
	isSet bool
}

func (v NullableClassLocaleData) Get() *ClassLocaleData {
	return v.value
}

func (v *NullableClassLocaleData) Set(val *ClassLocaleData) {
	v.value = val
	v.isSet = true
}

func (v NullableClassLocaleData) IsSet() bool {
	return v.isSet
}

func (v *NullableClassLocaleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassLocaleData(val *ClassLocaleData) *NullableClassLocaleData {
	return &NullableClassLocaleData{value: val, isSet: true}
}

func (v NullableClassLocaleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassLocaleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


