/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeactivateClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeactivateClass{}

// DeactivateClass struct for DeactivateClass
type DeactivateClass struct {
	Data DeactivateClassData `json:"data"`
}

type _DeactivateClass DeactivateClass

// NewDeactivateClass instantiates a new DeactivateClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeactivateClass(data DeactivateClassData) *DeactivateClass {
	this := DeactivateClass{}
	this.Data = data
	return &this
}

// NewDeactivateClassWithDefaults instantiates a new DeactivateClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeactivateClassWithDefaults() *DeactivateClass {
	this := DeactivateClass{}
	return &this
}

// GetData returns the Data field value
func (o *DeactivateClass) GetData() DeactivateClassData {
	if o == nil {
		var ret DeactivateClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeactivateClass) GetDataOk() (*DeactivateClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeactivateClass) SetData(v DeactivateClassData) {
	o.Data = v
}

func (o DeactivateClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeactivateClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeactivateClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeactivateClass := _DeactivateClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeactivateClass)

	if err != nil {
		return err
	}

	*o = DeactivateClass(varDeactivateClass)

	return err
}

type NullableDeactivateClass struct {
	value *DeactivateClass
	isSet bool
}

func (v NullableDeactivateClass) Get() *DeactivateClass {
	return v.value
}

func (v *NullableDeactivateClass) Set(val *DeactivateClass) {
	v.value = val
	v.isSet = true
}

func (v NullableDeactivateClass) IsSet() bool {
	return v.isSet
}

func (v *NullableDeactivateClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeactivateClass(val *DeactivateClass) *NullableDeactivateClass {
	return &NullableDeactivateClass{value: val, isSet: true}
}

func (v NullableDeactivateClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeactivateClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


