/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceLocale type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceLocale{}

// PlaceLocale struct for PlaceLocale
type PlaceLocale struct {
	Data PlaceLocaleData `json:"data"`
}

type _PlaceLocale PlaceLocale

// NewPlaceLocale instantiates a new PlaceLocale object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceLocale(data PlaceLocaleData) *PlaceLocale {
	this := PlaceLocale{}
	this.Data = data
	return &this
}

// NewPlaceLocaleWithDefaults instantiates a new PlaceLocale object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceLocaleWithDefaults() *PlaceLocale {
	this := PlaceLocale{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceLocale) GetData() PlaceLocaleData {
	if o == nil {
		var ret PlaceLocaleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceLocale) GetDataOk() (*PlaceLocaleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PlaceLocale) SetData(v PlaceLocaleData) {
	o.Data = v
}

func (o PlaceLocale) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceLocale) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PlaceLocale) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceLocale := _PlaceLocale{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceLocale)

	if err != nil {
		return err
	}

	*o = PlaceLocale(varPlaceLocale)

	return err
}

type NullablePlaceLocale struct {
	value *PlaceLocale
	isSet bool
}

func (v NullablePlaceLocale) Get() *PlaceLocale {
	return v.value
}

func (v *NullablePlaceLocale) Set(val *PlaceLocale) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceLocale) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceLocale) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceLocale(val *PlaceLocale) *NullablePlaceLocale {
	return &NullablePlaceLocale{value: val, isSet: true}
}

func (v NullablePlaceLocale) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceLocale) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


