/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassLocale type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassLocale{}

// ClassLocale struct for ClassLocale
type ClassLocale struct {
	Data ClassLocaleData `json:"data"`
}

type _ClassLocale ClassLocale

// NewClassLocale instantiates a new ClassLocale object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassLocale(data ClassLocaleData) *ClassLocale {
	this := ClassLocale{}
	this.Data = data
	return &this
}

// NewClassLocaleWithDefaults instantiates a new ClassLocale object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassLocaleWithDefaults() *ClassLocale {
	this := ClassLocale{}
	return &this
}

// GetData returns the Data field value
func (o *ClassLocale) GetData() ClassLocaleData {
	if o == nil {
		var ret ClassLocaleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ClassLocale) GetDataOk() (*ClassLocaleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ClassLocale) SetData(v ClassLocaleData) {
	o.Data = v
}

func (o ClassLocale) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassLocale) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ClassLocale) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassLocale := _ClassLocale{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassLocale)

	if err != nil {
		return err
	}

	*o = ClassLocale(varClassLocale)

	return err
}

type NullableClassLocale struct {
	value *ClassLocale
	isSet bool
}

func (v NullableClassLocale) Get() *ClassLocale {
	return v.value
}

func (v *NullableClassLocale) Set(val *ClassLocale) {
	v.value = val
	v.isSet = true
}

func (v NullableClassLocale) IsSet() bool {
	return v.isSet
}

func (v *NullableClassLocale) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassLocale(val *ClassLocale) *NullableClassLocale {
	return &NullableClassLocale{value: val, isSet: true}
}

func (v NullableClassLocale) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassLocale) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


