/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClassData{}

// UpdateClassData struct for UpdateClassData
type UpdateClassData struct {
	// class code
	Id string `json:"id"`
	// Resource type
	Type string `json:"type"`
	Attributes UpdateClassDataAttributes `json:"attributes"`
}

type _UpdateClassData UpdateClassData

// NewUpdateClassData instantiates a new UpdateClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClassData(id string, type_ string, attributes UpdateClassDataAttributes) *UpdateClassData {
	this := UpdateClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateClassDataWithDefaults instantiates a new UpdateClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClassDataWithDefaults() *UpdateClassData {
	this := UpdateClassData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateClassData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateClassData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateClassData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateClassData) GetAttributes() UpdateClassDataAttributes {
	if o == nil {
		var ret UpdateClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateClassData) GetAttributesOk() (*UpdateClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateClassData) SetAttributes(v UpdateClassDataAttributes) {
	o.Attributes = v
}

func (o UpdateClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateClassData := _UpdateClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateClassData)

	if err != nil {
		return err
	}

	*o = UpdateClassData(varUpdateClassData)

	return err
}

type NullableUpdateClassData struct {
	value *UpdateClassData
	isSet bool
}

func (v NullableUpdateClassData) Get() *UpdateClassData {
	return v.value
}

func (v *NullableUpdateClassData) Set(val *UpdateClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClassData(val *UpdateClassData) *NullableUpdateClassData {
	return &NullableUpdateClassData{value: val, isSet: true}
}

func (v NullableUpdateClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


