/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceLocalesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceLocalesCollection{}

// PlaceLocalesCollection struct for PlaceLocalesCollection
type PlaceLocalesCollection struct {
	Data []RelationshipDataObject `json:"data"`
	Included []PlaceLocaleData `json:"included"`
}

type _PlaceLocalesCollection PlaceLocalesCollection

// NewPlaceLocalesCollection instantiates a new PlaceLocalesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceLocalesCollection(data []RelationshipDataObject, included []PlaceLocaleData) *PlaceLocalesCollection {
	this := PlaceLocalesCollection{}
	this.Data = data
	this.Included = included
	return &this
}

// NewPlaceLocalesCollectionWithDefaults instantiates a new PlaceLocalesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceLocalesCollectionWithDefaults() *PlaceLocalesCollection {
	this := PlaceLocalesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *PlaceLocalesCollection) GetData() []RelationshipDataObject {
	if o == nil {
		var ret []RelationshipDataObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PlaceLocalesCollection) GetDataOk() ([]RelationshipDataObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PlaceLocalesCollection) SetData(v []RelationshipDataObject) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *PlaceLocalesCollection) GetIncluded() []PlaceLocaleData {
	if o == nil {
		var ret []PlaceLocaleData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *PlaceLocalesCollection) GetIncludedOk() ([]PlaceLocaleData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *PlaceLocalesCollection) SetIncluded(v []PlaceLocaleData) {
	o.Included = v
}

func (o PlaceLocalesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceLocalesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *PlaceLocalesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceLocalesCollection := _PlaceLocalesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceLocalesCollection)

	if err != nil {
		return err
	}

	*o = PlaceLocalesCollection(varPlaceLocalesCollection)

	return err
}

type NullablePlaceLocalesCollection struct {
	value *PlaceLocalesCollection
	isSet bool
}

func (v NullablePlaceLocalesCollection) Get() *PlaceLocalesCollection {
	return v.value
}

func (v *NullablePlaceLocalesCollection) Set(val *PlaceLocalesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceLocalesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceLocalesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceLocalesCollection(val *PlaceLocalesCollection) *NullablePlaceLocalesCollection {
	return &NullablePlaceLocalesCollection{value: val, isSet: true}
}

func (v NullablePlaceLocalesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceLocalesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


