/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassLocalesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassLocalesCollection{}

// ClassLocalesCollection struct for ClassLocalesCollection
type ClassLocalesCollection struct {
	Data []RelationshipDataObject `json:"data"`
	Included []ClassLocaleData `json:"included"`
}

type _ClassLocalesCollection ClassLocalesCollection

// NewClassLocalesCollection instantiates a new ClassLocalesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassLocalesCollection(data []RelationshipDataObject, included []ClassLocaleData) *ClassLocalesCollection {
	this := ClassLocalesCollection{}
	this.Data = data
	this.Included = included
	return &this
}

// NewClassLocalesCollectionWithDefaults instantiates a new ClassLocalesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassLocalesCollectionWithDefaults() *ClassLocalesCollection {
	this := ClassLocalesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *ClassLocalesCollection) GetData() []RelationshipDataObject {
	if o == nil {
		var ret []RelationshipDataObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ClassLocalesCollection) GetDataOk() ([]RelationshipDataObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ClassLocalesCollection) SetData(v []RelationshipDataObject) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *ClassLocalesCollection) GetIncluded() []ClassLocaleData {
	if o == nil {
		var ret []ClassLocaleData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *ClassLocalesCollection) GetIncludedOk() ([]ClassLocaleData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *ClassLocalesCollection) SetIncluded(v []ClassLocaleData) {
	o.Included = v
}

func (o ClassLocalesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassLocalesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *ClassLocalesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassLocalesCollection := _ClassLocalesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassLocalesCollection)

	if err != nil {
		return err
	}

	*o = ClassLocalesCollection(varClassLocalesCollection)

	return err
}

type NullableClassLocalesCollection struct {
	value *ClassLocalesCollection
	isSet bool
}

func (v NullableClassLocalesCollection) Get() *ClassLocalesCollection {
	return v.value
}

func (v *NullableClassLocalesCollection) Set(val *ClassLocalesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableClassLocalesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableClassLocalesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassLocalesCollection(val *ClassLocalesCollection) *NullableClassLocalesCollection {
	return &NullableClassLocalesCollection{value: val, isSet: true}
}

func (v NullableClassLocalesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassLocalesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


