/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimetableData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimetableData{}

// TimetableData struct for TimetableData
type TimetableData struct {
	// place id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes TimetableDataAttributes `json:"attributes"`
}

type _TimetableData TimetableData

// NewTimetableData instantiates a new TimetableData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimetableData(id string, type_ string, attributes TimetableDataAttributes) *TimetableData {
	this := TimetableData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTimetableDataWithDefaults instantiates a new TimetableData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimetableDataWithDefaults() *TimetableData {
	this := TimetableData{}
	return &this
}

// GetId returns the Id field value
func (o *TimetableData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TimetableData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TimetableData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *TimetableData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TimetableData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TimetableData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TimetableData) GetAttributes() TimetableDataAttributes {
	if o == nil {
		var ret TimetableDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TimetableData) GetAttributesOk() (*TimetableDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TimetableData) SetAttributes(v TimetableDataAttributes) {
	o.Attributes = v
}

func (o TimetableData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimetableData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TimetableData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimetableData := _TimetableData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimetableData)

	if err != nil {
		return err
	}

	*o = TimetableData(varTimetableData)

	return err
}

type NullableTimetableData struct {
	value *TimetableData
	isSet bool
}

func (v NullableTimetableData) Get() *TimetableData {
	return v.value
}

func (v *NullableTimetableData) Set(val *TimetableData) {
	v.value = val
	v.isSet = true
}

func (v NullableTimetableData) IsSet() bool {
	return v.isSet
}

func (v *NullableTimetableData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimetableData(val *TimetableData) *NullableTimetableData {
	return &NullableTimetableData{value: val, isSet: true}
}

func (v NullableTimetableData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimetableData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


