/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceRelationshipsCityLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceRelationshipsCityLinks{}

// PlaceRelationshipsCityLinks struct for PlaceRelationshipsCityLinks
type PlaceRelationshipsCityLinks struct {
	// A link to the related resource
	Self string `json:"self"`
	// A link to the related resource
	Related string `json:"related"`
}

type _PlaceRelationshipsCityLinks PlaceRelationshipsCityLinks

// NewPlaceRelationshipsCityLinks instantiates a new PlaceRelationshipsCityLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceRelationshipsCityLinks(self string, related string) *PlaceRelationshipsCityLinks {
	this := PlaceRelationshipsCityLinks{}
	this.Self = self
	this.Related = related
	return &this
}

// NewPlaceRelationshipsCityLinksWithDefaults instantiates a new PlaceRelationshipsCityLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceRelationshipsCityLinksWithDefaults() *PlaceRelationshipsCityLinks {
	this := PlaceRelationshipsCityLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *PlaceRelationshipsCityLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *PlaceRelationshipsCityLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *PlaceRelationshipsCityLinks) SetSelf(v string) {
	o.Self = v
}

// GetRelated returns the Related field value
func (o *PlaceRelationshipsCityLinks) GetRelated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Related
}

// GetRelatedOk returns a tuple with the Related field value
// and a boolean to check if the value has been set.
func (o *PlaceRelationshipsCityLinks) GetRelatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Related, true
}

// SetRelated sets field value
func (o *PlaceRelationshipsCityLinks) SetRelated(v string) {
	o.Related = v
}

func (o PlaceRelationshipsCityLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceRelationshipsCityLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["related"] = o.Related
	return toSerialize, nil
}

func (o *PlaceRelationshipsCityLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"related",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceRelationshipsCityLinks := _PlaceRelationshipsCityLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceRelationshipsCityLinks)

	if err != nil {
		return err
	}

	*o = PlaceRelationshipsCityLinks(varPlaceRelationshipsCityLinks)

	return err
}

type NullablePlaceRelationshipsCityLinks struct {
	value *PlaceRelationshipsCityLinks
	isSet bool
}

func (v NullablePlaceRelationshipsCityLinks) Get() *PlaceRelationshipsCityLinks {
	return v.value
}

func (v *NullablePlaceRelationshipsCityLinks) Set(val *PlaceRelationshipsCityLinks) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceRelationshipsCityLinks) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceRelationshipsCityLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceRelationshipsCityLinks(val *PlaceRelationshipsCityLinks) *NullablePlaceRelationshipsCityLinks {
	return &NullablePlaceRelationshipsCityLinks{value: val, isSet: true}
}

func (v NullablePlaceRelationshipsCityLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceRelationshipsCityLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


