/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceLocaleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceLocaleData{}

// PlaceLocaleData struct for PlaceLocaleData
type PlaceLocaleData struct {
	// place_id + locale
	Id string `json:"id" validate:"regexp=^[0-9a-fA-F-]{36}:[a-z]{2}(?:-[A-Z]{2})?$"`
	Type string `json:"type"`
	Attributes PlaceLocaleDataAttributes `json:"attributes"`
}

type _PlaceLocaleData PlaceLocaleData

// NewPlaceLocaleData instantiates a new PlaceLocaleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceLocaleData(id string, type_ string, attributes PlaceLocaleDataAttributes) *PlaceLocaleData {
	this := PlaceLocaleData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPlaceLocaleDataWithDefaults instantiates a new PlaceLocaleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceLocaleDataWithDefaults() *PlaceLocaleData {
	this := PlaceLocaleData{}
	return &this
}

// GetId returns the Id field value
func (o *PlaceLocaleData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlaceLocaleData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlaceLocaleData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PlaceLocaleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceLocaleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceLocaleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PlaceLocaleData) GetAttributes() PlaceLocaleDataAttributes {
	if o == nil {
		var ret PlaceLocaleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PlaceLocaleData) GetAttributesOk() (*PlaceLocaleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PlaceLocaleData) SetAttributes(v PlaceLocaleDataAttributes) {
	o.Attributes = v
}

func (o PlaceLocaleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceLocaleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PlaceLocaleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceLocaleData := _PlaceLocaleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceLocaleData)

	if err != nil {
		return err
	}

	*o = PlaceLocaleData(varPlaceLocaleData)

	return err
}

type NullablePlaceLocaleData struct {
	value *PlaceLocaleData
	isSet bool
}

func (v NullablePlaceLocaleData) Get() *PlaceLocaleData {
	return v.value
}

func (v *NullablePlaceLocaleData) Set(val *PlaceLocaleData) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceLocaleData) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceLocaleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceLocaleData(val *PlaceLocaleData) *NullablePlaceLocaleData {
	return &NullablePlaceLocaleData{value: val, isSet: true}
}

func (v NullablePlaceLocaleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceLocaleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


