/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocaleForClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocaleForClass{}

// SetLocaleForClass struct for SetLocaleForClass
type SetLocaleForClass struct {
	Data SetLocaleForClassData `json:"data"`
}

type _SetLocaleForClass SetLocaleForClass

// NewSetLocaleForClass instantiates a new SetLocaleForClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocaleForClass(data SetLocaleForClassData) *SetLocaleForClass {
	this := SetLocaleForClass{}
	this.Data = data
	return &this
}

// NewSetLocaleForClassWithDefaults instantiates a new SetLocaleForClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocaleForClassWithDefaults() *SetLocaleForClass {
	this := SetLocaleForClass{}
	return &this
}

// GetData returns the Data field value
func (o *SetLocaleForClass) GetData() SetLocaleForClassData {
	if o == nil {
		var ret SetLocaleForClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClass) GetDataOk() (*SetLocaleForClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetLocaleForClass) SetData(v SetLocaleForClassData) {
	o.Data = v
}

func (o SetLocaleForClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocaleForClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetLocaleForClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocaleForClass := _SetLocaleForClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocaleForClass)

	if err != nil {
		return err
	}

	*o = SetLocaleForClass(varSetLocaleForClass)

	return err
}

type NullableSetLocaleForClass struct {
	value *SetLocaleForClass
	isSet bool
}

func (v NullableSetLocaleForClass) Get() *SetLocaleForClass {
	return v.value
}

func (v *NullableSetLocaleForClass) Set(val *SetLocaleForClass) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocaleForClass) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocaleForClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocaleForClass(val *SetLocaleForClass) *NullableSetLocaleForClass {
	return &NullableSetLocaleForClass{value: val, isSet: true}
}

func (v NullableSetLocaleForClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocaleForClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


