/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetPlaceTimetable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetPlaceTimetable{}

// SetPlaceTimetable struct for SetPlaceTimetable
type SetPlaceTimetable struct {
	Data TimetableData `json:"data"`
}

type _SetPlaceTimetable SetPlaceTimetable

// NewSetPlaceTimetable instantiates a new SetPlaceTimetable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetPlaceTimetable(data TimetableData) *SetPlaceTimetable {
	this := SetPlaceTimetable{}
	this.Data = data
	return &this
}

// NewSetPlaceTimetableWithDefaults instantiates a new SetPlaceTimetable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetPlaceTimetableWithDefaults() *SetPlaceTimetable {
	this := SetPlaceTimetable{}
	return &this
}

// GetData returns the Data field value
func (o *SetPlaceTimetable) GetData() TimetableData {
	if o == nil {
		var ret TimetableData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetPlaceTimetable) GetDataOk() (*TimetableData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetPlaceTimetable) SetData(v TimetableData) {
	o.Data = v
}

func (o SetPlaceTimetable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetPlaceTimetable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetPlaceTimetable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetPlaceTimetable := _SetPlaceTimetable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetPlaceTimetable)

	if err != nil {
		return err
	}

	*o = SetPlaceTimetable(varSetPlaceTimetable)

	return err
}

type NullableSetPlaceTimetable struct {
	value *SetPlaceTimetable
	isSet bool
}

func (v NullableSetPlaceTimetable) Get() *SetPlaceTimetable {
	return v.value
}

func (v *NullableSetPlaceTimetable) Set(val *SetPlaceTimetable) {
	v.value = val
	v.isSet = true
}

func (v NullableSetPlaceTimetable) IsSet() bool {
	return v.isSet
}

func (v *NullableSetPlaceTimetable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetPlaceTimetable(val *SetPlaceTimetable) *NullableSetPlaceTimetable {
	return &NullableSetPlaceTimetable{value: val, isSet: true}
}

func (v NullableSetPlaceTimetable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetPlaceTimetable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


