/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForClassDataAttributesLocalesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForClassDataAttributesLocalesInner{}

// SetLocalesForClassDataAttributesLocalesInner struct for SetLocalesForClassDataAttributesLocalesInner
type SetLocalesForClassDataAttributesLocalesInner struct {
	// Locale code
	Locale string `json:"locale"`
	// Locale name
	Name string `json:"name"`
}

type _SetLocalesForClassDataAttributesLocalesInner SetLocalesForClassDataAttributesLocalesInner

// NewSetLocalesForClassDataAttributesLocalesInner instantiates a new SetLocalesForClassDataAttributesLocalesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForClassDataAttributesLocalesInner(locale string, name string) *SetLocalesForClassDataAttributesLocalesInner {
	this := SetLocalesForClassDataAttributesLocalesInner{}
	this.Locale = locale
	this.Name = name
	return &this
}

// NewSetLocalesForClassDataAttributesLocalesInnerWithDefaults instantiates a new SetLocalesForClassDataAttributesLocalesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForClassDataAttributesLocalesInnerWithDefaults() *SetLocalesForClassDataAttributesLocalesInner {
	this := SetLocalesForClassDataAttributesLocalesInner{}
	return &this
}

// GetLocale returns the Locale field value
func (o *SetLocalesForClassDataAttributesLocalesInner) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassDataAttributesLocalesInner) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *SetLocalesForClassDataAttributesLocalesInner) SetLocale(v string) {
	o.Locale = v
}

// GetName returns the Name field value
func (o *SetLocalesForClassDataAttributesLocalesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassDataAttributesLocalesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetLocalesForClassDataAttributesLocalesInner) SetName(v string) {
	o.Name = v
}

func (o SetLocalesForClassDataAttributesLocalesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForClassDataAttributesLocalesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locale"] = o.Locale
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SetLocalesForClassDataAttributesLocalesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locale",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForClassDataAttributesLocalesInner := _SetLocalesForClassDataAttributesLocalesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForClassDataAttributesLocalesInner)

	if err != nil {
		return err
	}

	*o = SetLocalesForClassDataAttributesLocalesInner(varSetLocalesForClassDataAttributesLocalesInner)

	return err
}

type NullableSetLocalesForClassDataAttributesLocalesInner struct {
	value *SetLocalesForClassDataAttributesLocalesInner
	isSet bool
}

func (v NullableSetLocalesForClassDataAttributesLocalesInner) Get() *SetLocalesForClassDataAttributesLocalesInner {
	return v.value
}

func (v *NullableSetLocalesForClassDataAttributesLocalesInner) Set(val *SetLocalesForClassDataAttributesLocalesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForClassDataAttributesLocalesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForClassDataAttributesLocalesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForClassDataAttributesLocalesInner(val *SetLocalesForClassDataAttributesLocalesInner) *NullableSetLocalesForClassDataAttributesLocalesInner {
	return &NullableSetLocalesForClassDataAttributesLocalesInner{value: val, isSet: true}
}

func (v NullableSetLocalesForClassDataAttributesLocalesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForClassDataAttributesLocalesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


