/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassDataAttributes{}

// ClassDataAttributes struct for ClassDataAttributes
type ClassDataAttributes struct {
	// class status
	Status string `json:"status"`
	// class icon
	Icon string `json:"icon"`
	// class name
	Name string `json:"name"`
	// class creation date
	CreatedAt time.Time `json:"created_at"`
	// class last update date
	UpdatedAt time.Time `json:"updated_at"`
}

type _ClassDataAttributes ClassDataAttributes

// NewClassDataAttributes instantiates a new ClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassDataAttributes(status string, icon string, name string, createdAt time.Time, updatedAt time.Time) *ClassDataAttributes {
	this := ClassDataAttributes{}
	this.Status = status
	this.Icon = icon
	this.Name = name
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewClassDataAttributesWithDefaults instantiates a new ClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassDataAttributesWithDefaults() *ClassDataAttributes {
	this := ClassDataAttributes{}
	var name string = "New Class"
	this.Name = name
	return &this
}

// GetStatus returns the Status field value
func (o *ClassDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClassDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetIcon returns the Icon field value
func (o *ClassDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *ClassDataAttributes) SetIcon(v string) {
	o.Icon = v
}

// GetName returns the Name field value
func (o *ClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClassDataAttributes) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClassDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClassDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ClassDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ClassDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["icon"] = o.Icon
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"icon",
		"name",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassDataAttributes := _ClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassDataAttributes)

	if err != nil {
		return err
	}

	*o = ClassDataAttributes(varClassDataAttributes)

	return err
}

type NullableClassDataAttributes struct {
	value *ClassDataAttributes
	isSet bool
}

func (v NullableClassDataAttributes) Get() *ClassDataAttributes {
	return v.value
}

func (v *NullableClassDataAttributes) Set(val *ClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassDataAttributes(val *ClassDataAttributes) *NullableClassDataAttributes {
	return &NullableClassDataAttributes{value: val, isSet: true}
}

func (v NullableClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


