/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForClassDataAttributes{}

// SetLocalesForClassDataAttributes struct for SetLocalesForClassDataAttributes
type SetLocalesForClassDataAttributes struct {
	Locales []SetLocalesForClassDataAttributesLocalesInner `json:"locales"`
}

type _SetLocalesForClassDataAttributes SetLocalesForClassDataAttributes

// NewSetLocalesForClassDataAttributes instantiates a new SetLocalesForClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForClassDataAttributes(locales []SetLocalesForClassDataAttributesLocalesInner) *SetLocalesForClassDataAttributes {
	this := SetLocalesForClassDataAttributes{}
	this.Locales = locales
	return &this
}

// NewSetLocalesForClassDataAttributesWithDefaults instantiates a new SetLocalesForClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForClassDataAttributesWithDefaults() *SetLocalesForClassDataAttributes {
	this := SetLocalesForClassDataAttributes{}
	return &this
}

// GetLocales returns the Locales field value
func (o *SetLocalesForClassDataAttributes) GetLocales() []SetLocalesForClassDataAttributesLocalesInner {
	if o == nil {
		var ret []SetLocalesForClassDataAttributesLocalesInner
		return ret
	}

	return o.Locales
}

// GetLocalesOk returns a tuple with the Locales field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassDataAttributes) GetLocalesOk() ([]SetLocalesForClassDataAttributesLocalesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locales, true
}

// SetLocales sets field value
func (o *SetLocalesForClassDataAttributes) SetLocales(v []SetLocalesForClassDataAttributesLocalesInner) {
	o.Locales = v
}

func (o SetLocalesForClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locales"] = o.Locales
	return toSerialize, nil
}

func (o *SetLocalesForClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locales",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForClassDataAttributes := _SetLocalesForClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForClassDataAttributes)

	if err != nil {
		return err
	}

	*o = SetLocalesForClassDataAttributes(varSetLocalesForClassDataAttributes)

	return err
}

type NullableSetLocalesForClassDataAttributes struct {
	value *SetLocalesForClassDataAttributes
	isSet bool
}

func (v NullableSetLocalesForClassDataAttributes) Get() *SetLocalesForClassDataAttributes {
	return v.value
}

func (v *NullableSetLocalesForClassDataAttributes) Set(val *SetLocalesForClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForClassDataAttributes(val *SetLocalesForClassDataAttributes) *NullableSetLocalesForClassDataAttributes {
	return &NullableSetLocalesForClassDataAttributes{value: val, isSet: true}
}

func (v NullableSetLocalesForClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


