/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocaleForClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocaleForClassDataAttributes{}

// SetLocaleForClassDataAttributes struct for SetLocaleForClassDataAttributes
type SetLocaleForClassDataAttributes struct {
	// Locale code
	Locale string `json:"locale"`
	// Locale name
	Name string `json:"name"`
}

type _SetLocaleForClassDataAttributes SetLocaleForClassDataAttributes

// NewSetLocaleForClassDataAttributes instantiates a new SetLocaleForClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocaleForClassDataAttributes(locale string, name string) *SetLocaleForClassDataAttributes {
	this := SetLocaleForClassDataAttributes{}
	this.Locale = locale
	this.Name = name
	return &this
}

// NewSetLocaleForClassDataAttributesWithDefaults instantiates a new SetLocaleForClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocaleForClassDataAttributesWithDefaults() *SetLocaleForClassDataAttributes {
	this := SetLocaleForClassDataAttributes{}
	return &this
}

// GetLocale returns the Locale field value
func (o *SetLocaleForClassDataAttributes) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClassDataAttributes) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *SetLocaleForClassDataAttributes) SetLocale(v string) {
	o.Locale = v
}

// GetName returns the Name field value
func (o *SetLocaleForClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetLocaleForClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetLocaleForClassDataAttributes) SetName(v string) {
	o.Name = v
}

func (o SetLocaleForClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocaleForClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["locale"] = o.Locale
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SetLocaleForClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"locale",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocaleForClassDataAttributes := _SetLocaleForClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocaleForClassDataAttributes)

	if err != nil {
		return err
	}

	*o = SetLocaleForClassDataAttributes(varSetLocaleForClassDataAttributes)

	return err
}

type NullableSetLocaleForClassDataAttributes struct {
	value *SetLocaleForClassDataAttributes
	isSet bool
}

func (v NullableSetLocaleForClassDataAttributes) Get() *SetLocaleForClassDataAttributes {
	return v.value
}

func (v *NullableSetLocaleForClassDataAttributes) Set(val *SetLocaleForClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocaleForClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocaleForClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocaleForClassDataAttributes(val *SetLocaleForClassDataAttributes) *NullableSetLocaleForClassDataAttributes {
	return &NullableSetLocaleForClassDataAttributes{value: val, isSet: true}
}

func (v NullableSetLocaleForClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocaleForClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


