/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassDataRelationshipsParent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassDataRelationshipsParent{}

// ClassDataRelationshipsParent struct for ClassDataRelationshipsParent
type ClassDataRelationshipsParent struct {
	Links Links `json:"links"`
	Data Items `json:"data"`
}

type _ClassDataRelationshipsParent ClassDataRelationshipsParent

// NewClassDataRelationshipsParent instantiates a new ClassDataRelationshipsParent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassDataRelationshipsParent(links Links, data Items) *ClassDataRelationshipsParent {
	this := ClassDataRelationshipsParent{}
	this.Links = links
	this.Data = data
	return &this
}

// NewClassDataRelationshipsParentWithDefaults instantiates a new ClassDataRelationshipsParent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassDataRelationshipsParentWithDefaults() *ClassDataRelationshipsParent {
	this := ClassDataRelationshipsParent{}
	return &this
}

// GetLinks returns the Links field value
func (o *ClassDataRelationshipsParent) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ClassDataRelationshipsParent) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ClassDataRelationshipsParent) SetLinks(v Links) {
	o.Links = v
}

// GetData returns the Data field value
func (o *ClassDataRelationshipsParent) GetData() Items {
	if o == nil {
		var ret Items
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ClassDataRelationshipsParent) GetDataOk() (*Items, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ClassDataRelationshipsParent) SetData(v Items) {
	o.Data = v
}

func (o ClassDataRelationshipsParent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassDataRelationshipsParent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["links"] = o.Links
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ClassDataRelationshipsParent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"links",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassDataRelationshipsParent := _ClassDataRelationshipsParent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassDataRelationshipsParent)

	if err != nil {
		return err
	}

	*o = ClassDataRelationshipsParent(varClassDataRelationshipsParent)

	return err
}

type NullableClassDataRelationshipsParent struct {
	value *ClassDataRelationshipsParent
	isSet bool
}

func (v NullableClassDataRelationshipsParent) Get() *ClassDataRelationshipsParent {
	return v.value
}

func (v *NullableClassDataRelationshipsParent) Set(val *ClassDataRelationshipsParent) {
	v.value = val
	v.isSet = true
}

func (v NullableClassDataRelationshipsParent) IsSet() bool {
	return v.isSet
}

func (v *NullableClassDataRelationshipsParent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassDataRelationshipsParent(val *ClassDataRelationshipsParent) *NullableClassDataRelationshipsParent {
	return &NullableClassDataRelationshipsParent{value: val, isSet: true}
}

func (v NullableClassDataRelationshipsParent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassDataRelationshipsParent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


