/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForPlaceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForPlaceData{}

// SetLocalesForPlaceData struct for SetLocalesForPlaceData
type SetLocalesForPlaceData struct {
	// place_id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SetLocalesForPlaceDataAttributes `json:"attributes"`
}

type _SetLocalesForPlaceData SetLocalesForPlaceData

// NewSetLocalesForPlaceData instantiates a new SetLocalesForPlaceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForPlaceData(id string, type_ string, attributes SetLocalesForPlaceDataAttributes) *SetLocalesForPlaceData {
	this := SetLocalesForPlaceData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSetLocalesForPlaceDataWithDefaults instantiates a new SetLocalesForPlaceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForPlaceDataWithDefaults() *SetLocalesForPlaceData {
	this := SetLocalesForPlaceData{}
	return &this
}

// GetId returns the Id field value
func (o *SetLocalesForPlaceData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForPlaceData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetLocalesForPlaceData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SetLocalesForPlaceData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForPlaceData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SetLocalesForPlaceData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SetLocalesForPlaceData) GetAttributes() SetLocalesForPlaceDataAttributes {
	if o == nil {
		var ret SetLocalesForPlaceDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForPlaceData) GetAttributesOk() (*SetLocalesForPlaceDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SetLocalesForPlaceData) SetAttributes(v SetLocalesForPlaceDataAttributes) {
	o.Attributes = v
}

func (o SetLocalesForPlaceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForPlaceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SetLocalesForPlaceData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForPlaceData := _SetLocalesForPlaceData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForPlaceData)

	if err != nil {
		return err
	}

	*o = SetLocalesForPlaceData(varSetLocalesForPlaceData)

	return err
}

type NullableSetLocalesForPlaceData struct {
	value *SetLocalesForPlaceData
	isSet bool
}

func (v NullableSetLocalesForPlaceData) Get() *SetLocalesForPlaceData {
	return v.value
}

func (v *NullableSetLocalesForPlaceData) Set(val *SetLocalesForPlaceData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForPlaceData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForPlaceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForPlaceData(val *SetLocalesForPlaceData) *NullableSetLocalesForPlaceData {
	return &NullableSetLocalesForPlaceData{value: val, isSet: true}
}

func (v NullableSetLocalesForPlaceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForPlaceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


