/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetPlaceLocale type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetPlaceLocale{}

// SetPlaceLocale struct for SetPlaceLocale
type SetPlaceLocale struct {
	Data SetPlaceLocaleData `json:"data"`
}

type _SetPlaceLocale SetPlaceLocale

// NewSetPlaceLocale instantiates a new SetPlaceLocale object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetPlaceLocale(data SetPlaceLocaleData) *SetPlaceLocale {
	this := SetPlaceLocale{}
	this.Data = data
	return &this
}

// NewSetPlaceLocaleWithDefaults instantiates a new SetPlaceLocale object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetPlaceLocaleWithDefaults() *SetPlaceLocale {
	this := SetPlaceLocale{}
	return &this
}

// GetData returns the Data field value
func (o *SetPlaceLocale) GetData() SetPlaceLocaleData {
	if o == nil {
		var ret SetPlaceLocaleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SetPlaceLocale) GetDataOk() (*SetPlaceLocaleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SetPlaceLocale) SetData(v SetPlaceLocaleData) {
	o.Data = v
}

func (o SetPlaceLocale) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetPlaceLocale) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SetPlaceLocale) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetPlaceLocale := _SetPlaceLocale{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetPlaceLocale)

	if err != nil {
		return err
	}

	*o = SetPlaceLocale(varSetPlaceLocale)

	return err
}

type NullableSetPlaceLocale struct {
	value *SetPlaceLocale
	isSet bool
}

func (v NullableSetPlaceLocale) Get() *SetPlaceLocale {
	return v.value
}

func (v *NullableSetPlaceLocale) Set(val *SetPlaceLocale) {
	v.value = val
	v.isSet = true
}

func (v NullableSetPlaceLocale) IsSet() bool {
	return v.isSet
}

func (v *NullableSetPlaceLocale) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetPlaceLocale(val *SetPlaceLocale) *NullableSetPlaceLocale {
	return &NullableSetPlaceLocale{value: val, isSet: true}
}

func (v NullableSetPlaceLocale) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetPlaceLocale) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


