/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClassRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassRelationships{}

// ClassRelationships struct for ClassRelationships
type ClassRelationships struct {
	Parent ClassRelationshipsParent `json:"parent"`
}

type _ClassRelationships ClassRelationships

// NewClassRelationships instantiates a new ClassRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassRelationships(parent ClassRelationshipsParent) *ClassRelationships {
	this := ClassRelationships{}
	this.Parent = parent
	return &this
}

// NewClassRelationshipsWithDefaults instantiates a new ClassRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassRelationshipsWithDefaults() *ClassRelationships {
	this := ClassRelationships{}
	return &this
}

// GetParent returns the Parent field value
func (o *ClassRelationships) GetParent() ClassRelationshipsParent {
	if o == nil {
		var ret ClassRelationshipsParent
		return ret
	}

	return o.Parent
}

// GetParentOk returns a tuple with the Parent field value
// and a boolean to check if the value has been set.
func (o *ClassRelationships) GetParentOk() (*ClassRelationshipsParent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parent, true
}

// SetParent sets field value
func (o *ClassRelationships) SetParent(v ClassRelationshipsParent) {
	o.Parent = v
}

func (o ClassRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parent"] = o.Parent
	return toSerialize, nil
}

func (o *ClassRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassRelationships := _ClassRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassRelationships)

	if err != nil {
		return err
	}

	*o = ClassRelationships(varClassRelationships)

	return err
}

type NullableClassRelationships struct {
	value *ClassRelationships
	isSet bool
}

func (v NullableClassRelationships) Get() *ClassRelationships {
	return v.value
}

func (v *NullableClassRelationships) Set(val *ClassRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableClassRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableClassRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassRelationships(val *ClassRelationships) *NullableClassRelationships {
	return &NullableClassRelationships{value: val, isSet: true}
}

func (v NullableClassRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


