/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceVerifiedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceVerifiedData{}

// UpdatePlaceVerifiedData struct for UpdatePlaceVerifiedData
type UpdatePlaceVerifiedData struct {
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdatePlaceVerifiedDataAttributes `json:"attributes"`
}

type _UpdatePlaceVerifiedData UpdatePlaceVerifiedData

// NewUpdatePlaceVerifiedData instantiates a new UpdatePlaceVerifiedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceVerifiedData(id uuid.UUID, type_ string, attributes UpdatePlaceVerifiedDataAttributes) *UpdatePlaceVerifiedData {
	this := UpdatePlaceVerifiedData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdatePlaceVerifiedDataWithDefaults instantiates a new UpdatePlaceVerifiedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceVerifiedDataWithDefaults() *UpdatePlaceVerifiedData {
	this := UpdatePlaceVerifiedData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdatePlaceVerifiedData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceVerifiedData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdatePlaceVerifiedData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdatePlaceVerifiedData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceVerifiedData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdatePlaceVerifiedData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdatePlaceVerifiedData) GetAttributes() UpdatePlaceVerifiedDataAttributes {
	if o == nil {
		var ret UpdatePlaceVerifiedDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceVerifiedData) GetAttributesOk() (*UpdatePlaceVerifiedDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdatePlaceVerifiedData) SetAttributes(v UpdatePlaceVerifiedDataAttributes) {
	o.Attributes = v
}

func (o UpdatePlaceVerifiedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceVerifiedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdatePlaceVerifiedData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceVerifiedData := _UpdatePlaceVerifiedData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceVerifiedData)

	if err != nil {
		return err
	}

	*o = UpdatePlaceVerifiedData(varUpdatePlaceVerifiedData)

	return err
}

type NullableUpdatePlaceVerifiedData struct {
	value *UpdatePlaceVerifiedData
	isSet bool
}

func (v NullableUpdatePlaceVerifiedData) Get() *UpdatePlaceVerifiedData {
	return v.value
}

func (v *NullableUpdatePlaceVerifiedData) Set(val *UpdatePlaceVerifiedData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceVerifiedData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceVerifiedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceVerifiedData(val *UpdatePlaceVerifiedData) *NullableUpdatePlaceVerifiedData {
	return &NullableUpdatePlaceVerifiedData{value: val, isSet: true}
}

func (v NullableUpdatePlaceVerifiedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceVerifiedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


