/*
Cifra SSO REST API

SSO REST API for Cifra domain

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeactivateClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeactivateClassData{}

// DeactivateClassData struct for DeactivateClassData
type DeactivateClassData struct {
	// class_code + locale
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes DeactivateClassDataAttributes `json:"attributes"`
}

type _DeactivateClassData DeactivateClassData

// NewDeactivateClassData instantiates a new DeactivateClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeactivateClassData(id string, type_ string, attributes DeactivateClassDataAttributes) *DeactivateClassData {
	this := DeactivateClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDeactivateClassDataWithDefaults instantiates a new DeactivateClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeactivateClassDataWithDefaults() *DeactivateClassData {
	this := DeactivateClassData{}
	return &this
}

// GetId returns the Id field value
func (o *DeactivateClassData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeactivateClassData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeactivateClassData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DeactivateClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeactivateClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeactivateClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DeactivateClassData) GetAttributes() DeactivateClassDataAttributes {
	if o == nil {
		var ret DeactivateClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DeactivateClassData) GetAttributesOk() (*DeactivateClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DeactivateClassData) SetAttributes(v DeactivateClassDataAttributes) {
	o.Attributes = v
}

func (o DeactivateClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeactivateClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DeactivateClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeactivateClassData := _DeactivateClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeactivateClassData)

	if err != nil {
		return err
	}

	*o = DeactivateClassData(varDeactivateClassData)

	return err
}

type NullableDeactivateClassData struct {
	value *DeactivateClassData
	isSet bool
}

func (v NullableDeactivateClassData) Get() *DeactivateClassData {
	return v.value
}

func (v *NullableDeactivateClassData) Set(val *DeactivateClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeactivateClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeactivateClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeactivateClassData(val *DeactivateClassData) *NullableDeactivateClassData {
	return &NullableDeactivateClassData{value: val, isSet: true}
}

func (v NullableDeactivateClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeactivateClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


