/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClass{}

// UpdateClass struct for UpdateClass
type UpdateClass struct {
	Data UpdateClassData `json:"data"`
}

type _UpdateClass UpdateClass

// NewUpdateClass instantiates a new UpdateClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClass(data UpdateClassData) *UpdateClass {
	this := UpdateClass{}
	this.Data = data
	return &this
}

// NewUpdateClassWithDefaults instantiates a new UpdateClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClassWithDefaults() *UpdateClass {
	this := UpdateClass{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateClass) GetData() UpdateClassData {
	if o == nil {
		var ret UpdateClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateClass) GetDataOk() (*UpdateClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateClass) SetData(v UpdateClassData) {
	o.Data = v
}

func (o UpdateClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateClass := _UpdateClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateClass)

	if err != nil {
		return err
	}

	*o = UpdateClass(varUpdateClass)

	return err
}

type NullableUpdateClass struct {
	value *UpdateClass
	isSet bool
}

func (v NullableUpdateClass) Get() *UpdateClass {
	return v.value
}

func (v *NullableUpdateClass) Set(val *UpdateClass) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClass) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClass(val *UpdateClass) *NullableUpdateClass {
	return &NullableUpdateClass{value: val, isSet: true}
}

func (v NullableUpdateClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


