/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocalesForClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocalesForClassData{}

// SetLocalesForClassData struct for SetLocalesForClassData
type SetLocalesForClassData struct {
	// class_code
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SetLocalesForClassDataAttributes `json:"attributes"`
}

type _SetLocalesForClassData SetLocalesForClassData

// NewSetLocalesForClassData instantiates a new SetLocalesForClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocalesForClassData(id string, type_ string, attributes SetLocalesForClassDataAttributes) *SetLocalesForClassData {
	this := SetLocalesForClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSetLocalesForClassDataWithDefaults instantiates a new SetLocalesForClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocalesForClassDataWithDefaults() *SetLocalesForClassData {
	this := SetLocalesForClassData{}
	return &this
}

// GetId returns the Id field value
func (o *SetLocalesForClassData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetLocalesForClassData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SetLocalesForClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SetLocalesForClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SetLocalesForClassData) GetAttributes() SetLocalesForClassDataAttributes {
	if o == nil {
		var ret SetLocalesForClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SetLocalesForClassData) GetAttributesOk() (*SetLocalesForClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SetLocalesForClassData) SetAttributes(v SetLocalesForClassDataAttributes) {
	o.Attributes = v
}

func (o SetLocalesForClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocalesForClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SetLocalesForClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocalesForClassData := _SetLocalesForClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocalesForClassData)

	if err != nil {
		return err
	}

	*o = SetLocalesForClassData(varSetLocalesForClassData)

	return err
}

type NullableSetLocalesForClassData struct {
	value *SetLocalesForClassData
	isSet bool
}

func (v NullableSetLocalesForClassData) Get() *SetLocalesForClassData {
	return v.value
}

func (v *NullableSetLocalesForClassData) Set(val *SetLocalesForClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocalesForClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocalesForClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocalesForClassData(val *SetLocalesForClassData) *NullableSetLocalesForClassData {
	return &NullableSetLocalesForClassData{value: val, isSet: true}
}

func (v NullableSetLocalesForClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocalesForClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


