openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    Class:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - relationships
          properties:
            id:
              type: string
              format: string
              description: class code
            type:
              type: string
              enum:
                - place_class
            attributes:
              type: object
              required:
                - status
                - icon
                - name
                - created_at
                - updated_at
              properties:
                status:
                  type: string
                  description: class status
                icon:
                  type: string
                  format: uri
                  description: class icon
                name:
                  type: string
                  description: class name
                  default: New Class
                created_at:
                  type: string
                  format: date-time
                  description: class creation date
                updated_at:
                  type: string
                  format: date-time
                  description: class last update date
            relationships:
              type: object
              required:
                - parent
              properties:
                parent:
                  type: object
                  required:
                    - links
                    - data
                  properties:
                    links:
                      $ref: '#/components/schemas/PlaceRelationships/properties/city/properties/links'
                    data:
                      $ref: '#/components/schemas/PlaceLocalesCollection/properties/data/items'
    CreatePlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place id
            type:
              type: string
              enum:
                - place
            attributes:
              type: object
              properties:
                city_id:
                  type: string
                  format: uuid
                  description: city id
                distributor_id:
                  type: string
                  format: uuid
                  description: distributor id
                class:
                  type: string
                  description: place class
                ownership:
                  type: string
                  description: place ownership
                point:
                  type: object
                  required:
                    - lon
                    - lat
                  properties:
                    lon:
                      type: number
                      format: float
                      description: Longitude
                    lat:
                      type: number
                      format: float
                      description: Latitude
                locale:
                  type: string
                  description: locale
                name:
                  type: string
                  description: place name
                address:
                  type: string
                  description: place address
                description:
                  type: string
                  description: place description
                website:
                  type: string
                  format: uri
                  description: place website
                phone:
                  type: string
                  description: place phone number
    UpdatePlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place id
            type:
              type: string
              enum:
                - place
            attributes:
              type: object
              properties:
                class:
                  type: string
                  description: place class
                status:
                  type: string
                  description: place status
                website:
                  type: string
                  format: uri
                  description: place website
                phone:
                  type: string
                  description: place phone number
    Place:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place id
            type:
              type: string
              enum:
                - place
            attributes:
              type: object
              required:
                - city_id
                - class
                - status
                - verified
                - ownership
                - point
                - name
                - address
                - description
                - created_at
                - updated_at
              properties:
                city_id:
                  type: string
                  format: uuid
                  description: city id
                distributor_id:
                  type: string
                  format: uuid
                  description: distributor id
                class:
                  type: string
                  description: place class
                status:
                  type: string
                  description: place status
                verified:
                  type: boolean
                  description: is place verified
                ownership:
                  type: string
                  description: place ownership
                point:
                  $ref: '#/components/schemas/CreatePlace/properties/data/properties/attributes/properties/point'
                name:
                  type: string
                  description: place name
                address:
                  type: string
                  description: place address
                description:
                  type: string
                  description: place description
                website:
                  type: string
                  format: uri
                  description: place website
                phone:
                  type: string
                  description: place phone number
                created_at:
                  type: string
                  format: date-time
                  description: place creation date
                updated_at:
                  type: string
                  format: date-time
                  description: place last update date
    PlaceCollection:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Place/properties/data'
    PlaceRelationships:
      type: object
      required:
        - class
        - city
      properties:
        class:
          type: object
          required:
            - links
            - data
          properties:
            links:
              $ref: '#/components/schemas/PlaceRelationships/properties/city/properties/links'
            data:
              $ref: '#/components/schemas/PlaceLocalesCollection/properties/data/items'
        city:
          type: object
          required:
            - links
            - data
          properties:
            links:
              type: object
              required:
                - self
                - related
              properties:
                self:
                  type: string
                  format: uri
                  description: A link to the related resource
                related:
                  type: string
                  format: uri
                  description: A link to the related resource
            data:
              $ref: '#/components/schemas/PlaceLocalesCollection/properties/data/items'
        distributor:
          type: object
          required:
            - links
            - data
          properties:
            links:
              $ref: '#/components/schemas/PlaceRelationships/properties/city/properties/links'
            data:
              $ref: '#/components/schemas/PlaceLocalesCollection/properties/data/items'
    PlaceLocale:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: string
              description: place_id + locale
              pattern: '^[0-9a-fA-F-]{36}:[a-z]{2}(?:-[A-Z]{2})?$'
            type:
              type: string
              enum:
                - place_locale
            attributes:
              type: object
              required:
                - name
                - address
              properties:
                name:
                  type: string
                  description: Locale name
                address:
                  type: string
                  description: Locale address
                description:
                  type: string
                  description: Locale description
    PlaceLocalesCollection:
      type: object
      required:
        - data
        - included
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - type
              - id
            properties:
              type:
                type: string
                description: The type of the related resource
              id:
                type: string
                description: The ID of the related resource
        included:
          type: array
          items:
            $ref: '#/components/schemas/PlaceLocale/properties/data'
    SetPlaceLocale:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: string
              description: place_id + locale
              pattern: '^[0-9a-fA-F-]{36}:[a-z]{2}(?:-[A-Z]{2})?$'
            type:
              type: string
              enum:
                - place_locale
            attributes:
              required:
                - name
                - address
              properties:
                name:
                  type: string
                  description: Locale name
                address:
                  type: string
                  description: Locale address
                description:
                  type: string
                  description: Locale description
