openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra domain
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    Point:
      $ref: './spec/components/schemas/common/Point.yaml'
    RelationshipLinks:
      $ref: './spec/components/schemas/common/RelationshipLinks.yaml'
    RelationshipDataObject:
      $ref: './spec/components/schemas/common/RelationshipDataObject.yaml'
    PaginationData:
      $ref: './spec/components/schemas/common/PaginationData.yaml'

    Class:
      $ref: './spec/components/schemas/Class.yaml'
    ClassesCollection:
      $ref: './spec/components/schemas/ClassesCollection.yaml'
    ClassRelationships:
      $ref: './spec/components/schemas/ClassRelationships.yaml'
    ClassLocale:
      $ref: './spec/components/schemas/ClassLocale.yaml'
    ClassLocalesCollection:
        $ref: './spec/components/schemas/ClassLocalesCollection.yaml'
    CreateClass:
      $ref: './spec/components/schemas/CreateClass.yaml'
    UpdateClass:
      $ref: './spec/components/schemas/UpdateClass.yaml'
    DeactivateClass:
      $ref: './spec/components/schemas/DeactivateClass.yaml'
    SetLocalesForClass:
      $ref: './spec/components/schemas/SetLocalesForClass.yaml'

    Place:
      $ref: './spec/components/schemas/Place.yaml'
    PlacesCollection:
      $ref: './spec/components/schemas/PlacesCollection.yaml'
    PlaceRelationships:
      $ref: './spec/components/schemas/PlaceRelationships.yaml'
    CreatePlace:
      $ref: './spec/components/schemas/CreatePlace.yaml'
    UpdatePlace:
      $ref: './spec/components/schemas/UpdatePlace.yaml'
    PlaceLocale:
      $ref: './spec/components/schemas/PlaceLocale.yaml'
    PlaceLocalesCollection:
      $ref: './spec/components/schemas/PlaceLocalesCollection.yaml'
    SetLocalesForPlace:
      $ref: './spec/components/schemas/SetLocalesForPlace.yaml'

    Timetable:
      $ref: './spec/components/schemas/Timetable.yaml'
    TimetableInterval:
      $ref: './spec/components/schemas/TimeInterval.yaml'
    TimeMoment:
      $ref: './spec/components/schemas/TimeMoment.yaml'
    SetPlaceTimetable:
      $ref: './spec/components/schemas/SetPlaceTimetable.yaml'
